name: ibaal-sign
options:
  bundleIdPrefix: com.ibaal
  deploymentTarget:
    iOS: "15.0"
  xcodeVersion: "15.0"

settings:
  base:
    PRODUCT_NAME: ibaal-sign
    SWIFT_VERSION: "5.0"
    TARGETED_DEVICE_FAMILY: "1,2"

targets:
  ibaal-sign:
    type: application
    platform: iOS
    deploymentTarget: "15.0"
    sources:
      - path: ibaal-sign
    info:
      path: ibaal-sign/Info.plist
    settings:
      base:
        INFOPLIST_FILE: ibaal-sign/Info.plist
        PRODUCT_BUNDLE_IDENTIFIER: com.ibaal.sign
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
        CODE_SIGNING_REQUIRED: "NO"
        CODE_SIGN_IDENTITY: ""
        CODE_SIGNING_ALLOWED: "NO"
